In [2]:
import pandas as pd
import numpy as np

# LIMPIEZA TABLA PRODUCTOS

In [11]:
# HACEMOS UNA COPIA DE LA TABLA PRODUCTO_RAW PARA PRODUCTO_CLEAN Y LO LLAMAMOS
Producto_Raw = pd.read_csv('../Data/Raw/productos.csv')
Producto_Clean = Producto_Raw.copy()
Producto_Clean.head(10)

   id_producto         nombre_producto     categoria precio_base
0            1           Laptop Pro 14   Electrónica       $1200
1            2       Mouse Inalámbrico          Elec          35
2            3        Teclado Mecánico  electtronica          89
3            4             Monitor 24"   Electrónica         180
4            5     Audífonos Bluetooth   Electronica         $75
5            6          Cargador USB-C    Eletrónica         -25
6            7            Smartphone X   Electrónica         799
7            8              Tablet 10"   Electrónica        $250
8            9  Impresora Multifunción       Oficina         220
9           10        Silla Ergonómica       Muebles         310

In [12]:
# Quitar espacios en columnas de texto
Producto_Clean['nombre_producto'] = Producto_Clean['nombre_producto'].str.strip()
Producto_Clean['categoria'] = Producto_Clean['categoria'].str.strip()
Producto_Clean['precio_base'] = Producto_Clean['precio_base'].str.strip()

In [13]:
# Quitar símbolo $ y convertir a número
Producto_Clean['precio_base'] = Producto_Clean['precio_base'].str.replace('$','',regex=False)
Producto_Clean['precio_base'] = pd.to_numeric(Producto_Clean['precio_base'], errors='coerce')

In [ ]:
# Combertir un numero negativo a positivo
Producto_Clean['precio_base'] = abs(Producto_Clean['precio_base'])

In [ ]:
# Remplazar la palabra mal escrita por la buena
Producto_Clean['categoria'] = Producto_Clean['categoria'].replace({
    'Elec' : 'Electrónica',
    'electtronica' : 'Electrónica',
    'Eletrónica' : 'Electrónica',
    'Electronica' : 'Electrónica',
    'eletronica' : 'Electrónica',
    'ElecTrónica' : 'Electrónica',
})

In [ ]:
# Remplazar el " con nada
Producto_Clean['nombre_producto'] = Producto_Clean['nombre_producto'].str.replace('"','', regex=False)

In [29]:
#
Producto_Clean.to_csv('../Data/Clean/Producto_Clean.csv', index=False)

# LIMPIEZA TABLA PEDIDOS

In [ ]:
# HACEMOS UNA COPIA DE LA TABLA PRODUCTO_RAW PARA PRODUCTO_CLEAN Y LO LLAMAMOS
Pedidos_Raw = pd.read_csv('../Data/Raw/pedidos.csv')
Pedidos_Clean = Pedidos_Raw.copy()
Pedidos_Clean.head(20)

    id_pedido  id_producto id_cliente fecha_pedido  cantidad
0           1            4      C0002   2025-01-05         3
1           2            8      C0015   14/01/2025         2
2           3            4      C0035   01-23-2025         1
3           4           19      C0028   2025-02-01         1
4           5            1      C0006   10/02/2025         2
5           6            8      C0033   02-19-2025         8
6           7            1      C0036   2025-02-28         2
7           8           18      C0027   09/03/2025         2
8           9           15      C0038   03-18-2025         3
9          10            1      C0011   2025-03-27         5
10         11           99      C0018   05/04/2025         2
11         12            7      C0022   04-14-2025         1
12         13            3      C0025   2025-04-23         1
13         14           12      C0023   02/05/2025         8
14         15            9      C0003   05-11-2025         6
15         16           18      C0008   2025-05-20         5
16         17            3      C0036   29/05/2025         3
17         18           20      C0024   06-07-2025         8
18         19            7      C0005   2025-06-16         1
19         20            8      C0019   25/06/2025         1

In [32]:
# Eliminar espacios en blanco al inicio y final
Pedidos_Clean['id_cliente'] = Pedidos_Clean['id_cliente'].str.strip()
Pedidos_Clean['fecha_pedido'] = Pedidos_Clean['fecha_pedido'].str.strip()

In [55]:
# Transformar los tipos de datos de al columnas
def convertir_fecha(fecha):
    for formato in ['%Y-%m-%d', '%d/%m/%Y', '%m-%d-%Y']:
        try:
            return pd.to_datetime(fecha, format=formato)
        except:
            continue
    return pd.NaT

Pedidos_Clean['fecha_pedido'] = Pedidos_Clean['fecha_pedido'].apply(convertir_fecha)

In [ ]:
# Eliminar duplicados
Pedidos_Clean = Pedidos_Clean.drop_duplicates()

In [50]:
# FLAG, 1 SI EL PRODUCTO EXISTE Y 0 SI NO EXISTE
ids_validos = Producto_Clean['id_producto']
Pedidos_Clean['flag_producto_valido'] = Pedidos_Clean['id_producto'].isin(ids_validos).astype(int)

In [ ]:
# Descargar el nuevo csv limpio
Pedidos_Clean.to_csv("../Data/Clean/pedidos_clean.csv", index=False)

# LIMPIEZA TABLA ALMACENES

In [6]:
# HACEMOS UNA COPIA DE LA TABLA Almacenes_Raw PARA Almacenes_Clean Y LO LLAMAMOS
Almacenes_Raw = pd.read_csv('../Data/Raw/almacenes.csv')
Almacenes_Clean = Almacenes_Raw.copy()
Almacenes_Clean.head(6)

   id_almacen ubicacion  capacidad
0           1      Lima      12000
1           2  Arequipa       8500
2           3  Trujillo       7000
3           4     cuzco       5000
4           5     Piura       6000
5           5    Piura        6000

In [7]:
# Eliminar espacio en blanco 
Almacenes_Clean['ubicacion'] = Almacenes_Clean['ubicacion'].str.strip()

In [10]:
# Eliminar duplicados
Almacenes_Clean = Almacenes_Clean.drop_duplicates()

In [12]:
# Descargar el nuevo csv limpio
Almacenes_Clean.to_csv('../Data/Clean/Almacenes_Clean.csv', index=False)

# LIMPIEZA TABLA LOGISTICA

In [15]:
# HACEMOS UNA COPIA DE LA TABLA Logistica_Raw PARA Logistica_Clean Y LO LLAMAMOS
Logistica_Raw = pd.read_csv('../Data/Raw/logistica.csv')
Logistica_Clean = Logistica_Raw.copy()
Logistica_Clean.head(10)

   id_pedido  id_almacen fecha_entrega_real estado_envio  costo_envio
0          1           5                NaN  En tránsito           22
1          2           1         22/01/2025  En tránsito           12
2          3           1         04/02/2025    Retrasado           18
3          4           4                NaN    Cancelado           18
4          5           3                NaN    Cancelado           28
5          6           5         2025-02-27    Entregado           18
6          7           1                NaN    Pendiente        10000
7          8           5         19/03/2025  En tránsito           12
8          9           2         2025-03-20    Entregado           20
9         10           5         2025-04-06    Entregado           12

In [16]:
# Eliminar espacios vacios
Logistica_Clean['fecha_entrega_real'] = Logistica_Clean['fecha_entrega_real'].str.strip()
Logistica_Clean['estado_envio'] = Logistica_Clean['estado_envio'].str.strip()

In [ ]:
# Transformar los tipos de datos de al columnas
def convertir_fecha(fecha):
    for formato in ['%Y-%m-%d', '%d/%m/%Y', '%m-%d-%Y']:
        try:
            return pd.to_datetime(fecha, format=formato)
        except:
            continue
    return pd.NaT

Logistica_Clean['fecha_entrega_real'] = Logistica_Clean['fecha_entrega_real'].apply(convertir_fecha)

In [ ]:
# Eliminar duplicados
Logistica_Clean = Logistica_Clean.drop_duplicates()

In [ ]:
# Usamos flag para costo_envio si es menor a 100 lo pone como 1 y si es mayor como 0
Logistica_Clean['flag_costo_atipico'] = (Logistica_Clean['costo_envio'] > 100).astype(int)

In [22]:
Logistica_Clean.to_csv('../Data/Clean/Logistica_Clean.csv', index=False)